import { lang } from "moment";

export const images = {
  backIcon: require("./back-icon.png"),
  // Snowflacke: require("./Snowflake.png"),
  Log: require("./lo.png"),
  welcomeImage: require("./welcome.png"),
  googleIcon: require('./google-icon.png'),
  appleIcon: require('./apple-icon.png'),
  completeAccount: require('./complete-account.png'),
  verifield: require('./verifield.png'),
  Snowflake: require("./Snowflake.png"),
  Logo: require("./Logo.png"),
  account: require("./account-logo.png"),
  onboardingSecondary: require("./Vector-secondary.png"),
  homeImage: require("./clipboard.png"),
  avatar: require("./avatar.png"),
  star: require("./star.png"),
  // avatarverified: require("./avatarverified"),
  // clipboard: require("./cliboard"),
  



  // star: require("./star.png"),
  ranking: require("./rating.png"),
  flag: require("./flag-france.png"),
  arrowdown: require("./arrowdown.png"),
  avatarverified: require("./avatarverified.png"),
  avatarnotverified: require("./avatar.png"),
  arrowright: require("./arrowright.png"),
  position: require("./jobtype_icon.png"),
  locationpin: require("./location_pin.png"),
  clockwhite: require("./clockwhite_icon.png"),
  calendarwhite: require("./calendarwhite_icon.png"),
  approvedwhite: require("./approval_white.png"),
  clipboard: require("./clipboard.png"),
  contactname: require("./contactname.png"),
  contactphone: require("./contactphone.png"),
  cardbackground: require("./jobcardbackground.png"),
  bag: require("./bag.png"),
  clipboardwithcheck: require("./clipboardwithcheck.png"),
  calendarnotification: require("./calendarnotification.png"),
  personcircled: require("./personcircled.png"),
  client: require("./client_icon.png"),
  clock: require("./clock_icon.png"),
  calendar: require("./calendar_icon.png"),
  radiochecked: require("./radio_checked.png"),
  radiounchecked: require("./radio_unchecked.png"),
  closeicon: require("./close_icon.png"),
  backbtn: require("./back_btn.png"),
  completed: require("./completed.png"),
  starred: require("./star_red_icon.png"),
  ratingred: require("./rating_red_icon.png"),
  logowithcaption: require("./logowithcaption.png"),
  logowithoutcaption: require("./logowithoutcaption.png"),
  logout: require('./logout.png'),
  greenstar: require("./greenstar_icon.png"),
  greenapproval: require("./greencheck_icon.png"),
  shoe: require("./shoe.png"),
  employer: require("./employer.png"),
  personalinfo: require("./personalinfo.png"),
  help: require("./help.png"),
  jobdetails: require("./jobdetails.png"),
  refer: require("./refer.png"),
  legal: require("./legal.png"),
  reddot: require("./reddot.png"),
  userimage: require("./userimage.png"),
  backgroundcheckmuted: require("./backgroundcheckmuted.png"),
  contactmuted: require("./contactmuted.png"),
  emailmuted: require("./emailmuted.png"),
  phonemuted: require("./phonemuted.png"),
  homeaddressmuted: require("./homeaddressmuted.png"),
  dobmuted: require("./dobmuted.png"),
  languagemuted: require("./languagemuted.png"),
  identityverificationmuted: require("./identityverificationmuted.png"),
  rating: require("./rating.png"),
  watermark: require("./watermark.png"),
  contactgreen: require("./contactgreen.png"),
  dobgreen: require("./dobgreen.png"),
  phonegreen: require("./phonegreen.png"),
  homeaddressgreen: require("./homeaddressgreen.png"),
  languagegreen: require("./languagegreen.png"),
  camera: require("./camera.png"),
  file: require("./file.png"),
  emergencycontact: require("./emergency_contact.png"),
  employmentagreement: require('./employment_agreement.png'),
  searchradius: require('./search_radius.png'),
  student: require('./student.png'),
  taxInfo: require('./tax_info.png'),
  transportation: require('./transportation.png'),
  certificate: require('./certificate.png'),
  health: require('./health.png'),
  report: require('./report.png'),
  document: require('./document.png'),
  radiooutline: require('./radio-outline.png'),
  radiofilled: require('./radio-filled.png'),
  verify: require('./verify.png'),
}
